# This is the docker-compose file to run Medplum's required background serivces
# It can be used to quickly run 2 services:
#   1) The Postgres database
#   2) The Redis cache
# You can start all services by running "docker-compose up"
version: '3.7'
name: pathcloud-medplum
services:
  apps:
    container_name: apps
    build:
      dockerfile: ./apps/docker/Dockerfile.medplum.apps
    # command: /bin/sh -c "/app/entrypoint.sh"
    command:
      - /bin/bash 
      - -c 
      - |
        cd app-admin && npm run dev
    expose: 
      - 3001
      - 3005
    ports:
      - 3001:3001
      - 3005:3005
    depends_on: [medplum] 
  medplum:
    container_name: medplum
    build:
      dockerfile: ./apps/docker/Dockerfile.medplum.server
    command: npm start
    expose: 
      - 80
      - 8103
    ports:
      - 8103:8103
    depends_on: [medplum-db, medplum-redis] 
  medplum-db:
    container_name: medplum-db
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=medplum
      - POSTGRES_PASSWORD=medplum
    volumes:
      - /mnt/datadrive/workspace/medplum-path/postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
      - /mnt/datadrive/workspace/medplum-path/postgres/:/docker-entrypoint-initdb.d/
      - postgres_medplum-path:/var/lib/postgresql/data
    command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf
    expose: [5432]
    # ports:
    #   - '5432:5432'
  medplum-redis:
    image: redis:6
    container_name: medplum-redis
    restart: always
    command: redis-server --requirepass medplum
    expose: [6379]
    # ports:
    #   - '6379:6379'

  nginx:
    # image: nginx:latest
    build: 
        context: ./nginx
        dockerfile: Dockerfile.ssl
    volumes:
      - /mnt/datadrive/workspace/medplum-path/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/datadrive/workspace/medplum-path/nginx/conf.d:/etc/nginx/conf.d
      - /mnt/datadrive/workspace/medplum-path/nginx/index.html:/usr/share/nginx/html/index.html
    restart: unless-stopped
    ports: 
      - 80:80
      - 443:443
volumes:
  postgres_medplum-path: {}
