version: '3.7'
services:
  orthanc:
    # image: osimis/orthanc:master-full
    build:
      context: ./app-containers/orthanc
      dockerfile: Dockerfile
    profiles: [orthanc]
    expose:
      - 8042
      - 4242
    ports:
      - 4242:4242   # DICOM server
      - 8042:8042   # HTTP server
    volumes:
      - orthanc_storage:/var/lib/orthanc/db
      # - ./app-containers/orthanc/plugins/OrthancGoogleCloudPlatform/auth-key-files/gcp-pathology-poc1_service_key.json:/usr/share/orthanc/plugins-config/gcp-pathology-poc1_service_key.json
      # - ./app-containers/orthanc/plugins/OrthancGoogleCloudPlatform/auth-key-files/gcp-wsi-dicom-rnd.json:/usr/share/orthanc/plugins-config/gcp-wsi-dicom-rnd.json
      # - ./app-containers/orthanc/plugins/plugins/orthanc-server-extensions/orthanc_ext:/python/orthanc_ext
      # - ./app-containers/orthanc/plugins/plugins/orthanc-server-extensions/entry_point.py:/python/entry_point.py

      - ./plugins/OrthancGoogleCloudPlatform/auth-key-files/gcp-pathology-poc1_service_key.json:/usr/share/orthanc/plugins-config/gcp-pathology-poc1_service_key.json
      - ./plugins/OrthancGoogleCloudPlatform/auth-key-files/gcp-wsi-dicom-rnd.json:/usr/share/orthanc/plugins-config/gcp-wsi-dicom-rnd.json
      - ./plugins/orthanc-server-extensions/orthanc_ext:/python/orthanc_ext
      - ./plugins/orthanc-server-extensions/entry_point.py:/python/entry_point.py
    environment:
      ORTHANC_NAME: "PathCloudPACS"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      GDCM_PLUGIN_ENABLED: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "false"
      OSIMIS_WEB_VIEWER1_ALPHA_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC_WEB_VIEWER_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      WSI_PLUGIN_ENABLED: "true"
      VOLVIEW_PLUGIN_ENABLED: "false"
      TCIA_PLUGIN_ENABLED: "true"
      ORTHANC__INGEST_TRANSCODING: "1.2.840.10008.1.2.4.50"    # Transcode: JPEG Baseline: "1.2.840.10008.1.2.4.50" Decompress="1.2.840.10008.1.2.1"
      # OHIF_PLUGIN_ENABLED: "true"
      # ORTHANC__PYTHON_SCRIPT: "/python/orthanc_ext/scripts/study_stable_to_rest.py"
    secrets:
      - orthanc.json
    restart: unless-stopped
secrets:
  orthanc.json:
    file: orthanc.json
volumes:
  orthanc_storage: {}