FROM node:18-bullseye
ARG MEDPLUM_CONFIG_FILE

WORKDIR /app

COPY package-lock.json /app/
COPY package.json /app/
COPY packages /app/packages
COPY scripts /app/scripts
COPY packages/server/${MEDPLUM_CONFIG_FILE} /app/packages/server/medplum.config.json

RUN npm ci

COPY turbo.json /app/
COPY tsconfig.json /app/
COPY tsdoc.json /app/
COPY api-extractor.json /app/


RUN npm run build:fast

WORKDIR /app/packages/server
# CMD ["npm", "start"]

# ENTRYPOINT ["tail", "-f", "/dev/null"]