FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

# COPY nginx.conf /etc/nginx/nginx.conf
COPY /apps/docker/nginx/conf.d/ /etc/nginx/conf.d/

COPY /apps/app-admin/dist /usr/share/nginx/html
# COPY /apps/app-admin/.env.defaults /usr/share/nginx/html/env.defaults
# COPY /apps/app-admin/.env.defaults /usr/share/nginx/html/.env.defaults
COPY /apps/app-admin/.env /usr/share/nginx/html/.env