version: '3.7'
services:
  viewer-ohif:
    container_name: viewer-ohif
    build: 
      # context: ./app-containers/viewer-ohif
      # dockerfile: ./container/Dockerfile
      dockerfile: Dockerfile
      args: 
        PUBLIC_URL: /viewer/
        QUICK_BUILD: true
    profiles: [applications]
    volumes:
      # - ./repo-viewer-ohif/platform/app/public/config/pathcloud_local.js:/usr/share/nginx/html/app-config.js
      - /mnt/datadrive/workspace/medplum-path/app-containers/viewer-ohif/repo-viewer-ohif/platform/app/public/config/pathcloud_local.js:/usr/share/nginx/html/app-config.js
    restart: unless-stopped
    expose: [80]
    ports:
      - 3010:80
  # ohif:
  #   build: 
  #     context: ./app-containers/viewer-ohif/ohif
  #     dockerfile: Dockerfile
  #     args: 
  #       PUBLIC_URL: /ohif/
  #       QUICK_BUILD: true
  #   restart: unless-stopped
  #   expose:
  #     - 80
  #   ports:
  #     - 3010:80